#!/usr/bin/env python3
"""Bake the reference illustration into src/art.js as data URIs.

Run once when the artwork changes:  python3 tools/bake-art.py

The game loads no external files — every other texture is drawn on a canvas at
runtime — and that is what lets one source run from file://, from Pages and as
an Artifact with no configuration. Fetching the artwork at runtime would break
that: a file:// page treats every file as its own origin, so reading the image
back into a canvas taints it, and the portrait card does exactly that kind of
canvas work. Embedding it as a data URI sidesteps loading entirely.
"""
import base64
import io
import os
import sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, 'assets', 'petty-ref.jpg')

# --- Crops, in coordinates of the raw phone screenshot -------------------
# The source is a screenshot: black letterbox bars, a "Crop" button and a back
# chevron all have to come off.
CHROME_TOP = 210          # below the bars and the Crop button
CHROME_BOTTOM = 2300      # above the lower bar

# Face: mid-forehead down to below the chin. Deliberately starts BELOW the
# hairline — his 3D hair sits above it, because hair loss is the health bar and
# baking the drawn hair in would fight the mechanic the game is built on.
FACE = (150, 940, 990, 1990)

# Side of the head: the drawing shows his left ear, jaw and the beard running
# behind it, so the head's side faces come out of the artwork too rather than
# being painted separately — painted ones sat lighter and flatter than the
# illustration and the seam at the box edge showed.
SIDE = (620, 1108, 1072, 1706)

# Box proportions, so crops are not distorted when mapped.
HEAD_ASPECT = 0.88 / 0.98          # front face: width / height
SIDE_ASPECT = 0.74 / 0.98          # side face: depth / height


def data_uri(img, fmt, quality=None):
    buf = io.BytesIO()
    if fmt == 'JPEG':
        img.convert('RGB').save(buf, 'JPEG', quality=quality or 86, optimize=True)
        mime = 'image/jpeg'
    else:
        img.save(buf, 'PNG', optimize=True)
        mime = 'image/png'
    raw = buf.getvalue()
    return 'data:%s;base64,%s' % (mime, base64.b64encode(raw).decode()), len(raw)


def main():
    if not os.path.exists(SRC):
        sys.exit('missing %s' % SRC)
    im = Image.open(SRC).convert('RGB')

    # --- face -----------------------------------------------------------
    x0, y0, x1, y1 = FACE
    # Widen or heighten the crop so its aspect matches the head, then squash to
    # a square texture: mapping a square texture onto the head's rectangle
    # un-squashes it, so proportions come out correct either way.
    w, h = x1 - x0, y1 - y0
    want_w = h * HEAD_ASPECT
    if want_w > w:
        pad = int((want_w - w) / 2)
        x0, x1 = x0 - pad, x1 + pad
    else:
        want_h = w / HEAD_ASPECT
        pad = int((want_h - h) / 2)
        y0, y1 = y0 - pad, y1 + pad
    face = im.crop((max(0, x0), max(0, y0), min(im.width, x1), min(im.height, y1)))
    face = face.resize((512, 512), Image.LANCZOS)
    face_uri, face_bytes = data_uri(face, 'JPEG', 88)

    # --- side ------------------------------------------------------------
    sx0, sy0, sx1, sy1 = SIDE
    sw, sh = sx1 - sx0, sy1 - sy0
    want = sh * SIDE_ASPECT
    if want > sw:
        pad = int((want - sw) / 2)
        sx0, sx1 = sx0 - pad, sx1 + pad
    else:
        want_h = sw / SIDE_ASPECT
        pad = int((want_h - sh) / 2)
        sy0, sy1 = sy0 - pad, sy1 + pad
    side = im.crop((max(0, sx0), max(0, sy0), min(im.width, sx1), min(im.height, sy1)))
    side = side.resize((384, 384), Image.LANCZOS)
    side_uri, side_bytes = data_uri(side, 'JPEG', 85)

    # --- cover: the whole illustration, chrome removed -------------------
    cover = im.crop((0, CHROME_TOP, im.width, CHROME_BOTTOM))
    scale = 760.0 / cover.width
    cover = cover.resize((760, int(cover.height * scale)), Image.LANCZOS)
    cover_uri, cover_bytes = data_uri(cover, 'JPEG', 82)

    out = os.path.join(ROOT, 'src', 'art.js')
    with open(out, 'w') as f:
        f.write('/* GENERATED by tools/bake-art.py — do not edit by hand.\n'
                ' *\n'
                ' * The reference illustration, embedded as data URIs. It is baked in\n'
                ' * rather than loaded because the game fetches nothing at runtime: that is\n'
                ' * what lets the same source run from file://, from GitHub Pages and as a\n'
                ' * published Artifact with no configuration. Re-run the script after\n'
                ' * changing assets/petty-ref.jpg.\n'
                ' */\n'
                'window.PP = window.PP || {};\n\n'
                'PP.Art = {\n')
        f.write("  face: '%s',\n\n" % face_uri)
        f.write("  side: '%s',\n\n" % side_uri)
        f.write("  cover: '%s'\n" % cover_uri)
        f.write('};\n')

    print('face  %6.1f KB  -> 512x512' % (face_bytes / 1024))
    print('side  %6.1f KB  -> 384x384' % (side_bytes / 1024))
    print('cover %6.1f KB  -> %dx%d' % (cover_bytes / 1024, cover.width, cover.height))
    print('wrote %s (%.1f KB)' % (out, os.path.getsize(out) / 1024))

    # Previews for eyeballing
    prev = os.environ.get('PREVIEW')
    if prev:
        face.save(os.path.join(prev, 'bake-face.png'))
        side.save(os.path.join(prev, 'bake-side.png'))
        cover.save(os.path.join(prev, 'bake-cover.png'))
        print('previews written to', prev)


if __name__ == '__main__':
    main()
