#!/usr/bin/env python3
"""Bake the reference illustration into src/art.js as data URIs.

Run once when the artwork changes:  python3 tools/bake-art.py

The game loads no external files — every other texture is drawn on a canvas at
runtime — and that is what lets one source run from file://, from Pages and as
an Artifact with no configuration. Fetching the artwork at runtime would break
that: a file:// page treats every file as its own origin, so reading the image
back into a canvas taints it, and the portrait card does exactly that kind of
canvas work. Embedding it as a data URI sidesteps loading entirely.
"""
import base64
import io
import os
import sys
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, 'assets', 'petty-ref.jpg')

# --- Crops, in coordinates of the raw phone screenshot -------------------
# The source is a screenshot: black letterbox bars, a "Crop" button and a back
# chevron all have to come off.
CHROME_TOP = 210          # below the bars and the Crop button
CHROME_BOTTOM = 2300      # above the lower bar

# Face: forehead down to below the beard, and wide enough to carry his ear.
#
# A SQUARE region of the source, so nothing is stretched. It is deliberately
# generous: `src/face.js` composites it into the head wrap through a soft
# elliptical mask, and the mask is what trims the corners — the yellow
# background scribble on the left, the maroon shirt at the bottom, the poster
# behind his shoulder on the right. Trimming here instead would mean re-baking
# every time the framing needs a nudge.
#
# It starts BELOW the drawn hairline. His 3D hair sits above it, because hair
# loss is the health bar and baking a second hairline in would fight the
# mechanic the whole game is built on.
FACE = (112, 990, 1112, 1990)

# No SIDE crop any more.
#
# The head used to be a box with a different picture on each face, and the
# sides took a second, closer crop of this same three-quarter portrait. The
# result was a man with a face on each side of his head, at a different scale
# and meeting the front at a hard 90-degree corner. The head is now one
# rounded mesh under one wrapped texture, and face.js paints the sides to
# match, so there is nothing for a second crop to do.


def data_uri(img, fmt, quality=None):
    buf = io.BytesIO()
    if fmt == 'JPEG':
        img.convert('RGB').save(buf, 'JPEG', quality=quality or 86, optimize=True)
        mime = 'image/jpeg'
    else:
        img.save(buf, 'PNG', optimize=True)
        mime = 'image/png'
    raw = buf.getvalue()
    return 'data:%s;base64,%s' % (mime, base64.b64encode(raw).decode()), len(raw)


def main():
    if not os.path.exists(SRC):
        sys.exit('missing %s' % SRC)
    im = Image.open(SRC).convert('RGB')

    # --- face -----------------------------------------------------------
    x0, y0, x1, y1 = FACE
    if (x1 - x0) != (y1 - y0):
        sys.exit('FACE must be square so the artwork is not stretched')
    face = im.crop((max(0, x0), max(0, y0), min(im.width, x1), min(im.height, y1)))
    face = face.resize((640, 640), Image.LANCZOS)
    face_uri, face_bytes = data_uri(face, 'JPEG', 88)

    # --- cover: the whole illustration, chrome removed -------------------
    cover = im.crop((0, CHROME_TOP, im.width, CHROME_BOTTOM))
    scale = 760.0 / cover.width
    cover = cover.resize((760, int(cover.height * scale)), Image.LANCZOS)
    cover_uri, cover_bytes = data_uri(cover, 'JPEG', 82)

    out = os.path.join(ROOT, 'src', 'art.js')
    with open(out, 'w') as f:
        f.write('/* GENERATED by tools/bake-art.py — do not edit by hand.\n'
                ' *\n'
                ' * The reference illustration, embedded as data URIs. It is baked in\n'
                ' * rather than loaded because the game fetches nothing at runtime: that is\n'
                ' * what lets the same source run from file://, from GitHub Pages and as a\n'
                ' * published Artifact with no configuration. Re-run the script after\n'
                ' * changing assets/petty-ref.jpg.\n'
                ' */\n'
                'window.PP = window.PP || {};\n\n'
                'PP.Art = {\n')
        f.write("  face: '%s',\n\n" % face_uri)
        f.write("  cover: '%s'\n" % cover_uri)
        f.write('};\n')

    print('face  %6.1f KB  -> 640x640' % (face_bytes / 1024))
    print('cover %6.1f KB  -> %dx%d' % (cover_bytes / 1024, cover.width, cover.height))
    print('wrote %s (%.1f KB)' % (out, os.path.getsize(out) / 1024))

    # Previews for eyeballing
    prev = os.environ.get('PREVIEW')
    if prev:
        face.save(os.path.join(prev, 'bake-face.png'))
        cover.save(os.path.join(prev, 'bake-cover.png'))
        print('previews written to', prev)


if __name__ == '__main__':
    main()
